"""One place for the AI disclosure and disclaimer shown on everything this project produces.

Three honest cases, which must not be blurred:
  "rules"        generated by software that was written with AI assistance. No AI model wrote
                 the words: they are extracted by programmed rules.
  "extraction"   the minutes themselves, tidied by that software; the words are the Mairie's.
  "site"         the website and documents themselves, written with AI assistance.
  "summary"      written by an AI model at run time.
  "translation"  translated by an AI model at run time.
Every notice says that no person has checked the output and that the original is authoritative.
The French, English and Dutch wording was itself written by the AI assistant and has not been
reviewed by a native speaker (see AI.md).
"""
AI_PAGE_URL = "https://github.com/mgifford/EchoDeMontolieu/blob/main/AI.md"
SOFTWARE = "Claude, an AI assistant from Anthropic"

_TEXT = {
    "en": {
        "heading": "AI disclosure.",
        "rules": ("This page was generated automatically by software that was written with AI assistance "
                  f"({SOFTWARE}). No AI model wrote its text: it is extracted from the minutes by programmed rules. "
                  "No person has checked it, and it can be wrong. The original documents are authoritative."),
        "extraction": ("This reading of the minutes was produced automatically by software that was written with AI "
                       f"assistance ({SOFTWARE}). No AI model rewrote the text: it is the Mairie's own wording, "
                       "extracted from the PDF, and pages read by OCR are marked and can be misread. No person has "
                       "checked it. The original PDF is authoritative."),
        "summary": ("This summary was written by an AI model ({model}) from the text of the minutes, using software "
                    "that was itself written with AI assistance. No person has checked it. It can contain errors, "
                    "omissions or invented details; do not rely on it for decisions. The minutes and the original "
                    "PDF are authoritative."),
        "translation": ("This text was translated by an AI model ({model}) from the French original, using software "
                        "written with AI assistance. No native speaker has reviewed it. It can contain errors or "
                        "change nuance; do not rely on it for decisions. The French text is authoritative."),
        "summary_translation": ("This is an AI translation ({model}) of a French summary that was itself written by an "
                                "AI model. No person has checked either. It can contain errors, omissions or "
                                "invented details; do not rely on it for decisions. The French minutes and the "
                                "original PDF are authoritative."),
        "site": ("This website and the software behind it were written with AI assistance "
                 f"({SOFTWARE}). Most pages are generated by programmed rules; where an AI model wrote or translated "
                 "a text, that text says so. No person has checked every page. The original documents are "
                 "authoritative."),
        "more": "About AI in this project",
        "short": "AI-assisted; not checked by a person",
    },
    "fr": {
        "heading": "Information sur l’IA.",
        "rules": ("Cette page a été produite automatiquement par un logiciel écrit avec l’aide d’une IA "
                  f"({SOFTWARE}). Aucun modèle d’IA n’a rédigé son texte : il est extrait des procès-verbaux par des "
                  "règles programmées. Personne ne l’a vérifié et il peut contenir des erreurs. Les documents "
                  "originaux font foi."),
        "extraction": ("Cette lecture du procès-verbal a été produite automatiquement par un logiciel écrit avec l’aide "
                       f"d’une IA ({SOFTWARE}). Aucun modèle d’IA n’a réécrit le texte : ce sont les termes de la "
                       "mairie, extraits du PDF ; les pages lues par OCR sont signalées et peuvent être mal lues. "
                       "Personne ne l’a vérifié. Le PDF original fait foi."),
        "summary": ("Ce résumé a été écrit par un modèle d’IA ({model}) à partir du texte du procès-verbal, avec un "
                    "logiciel lui-même écrit avec l’aide d’une IA. Personne ne l’a vérifié. Il peut contenir des "
                    "erreurs, des oublis ou des détails inventés ; ne vous y fiez pas pour prendre une décision. Le "
                    "procès-verbal et le PDF original font foi."),
        "translation": ("Ce texte a été traduit par un modèle d’IA ({model}) à partir de l’original français. Aucun "
                        "locuteur natif ne l’a relu. Il peut contenir des erreurs ou changer une nuance. Le texte "
                        "français fait foi."),
        "summary_translation": ("Traduction par IA ({model}) d’un résumé français lui-même écrit par un modèle d’IA. "
                                "Personne n’a vérifié ni l’un ni l’autre. Le procès-verbal français et le PDF "
                                "original font foi."),
        "site": ("Ce site et le logiciel qui le produit ont été écrits avec l’aide d’une IA "
                 f"({SOFTWARE}). La plupart des pages sont produites par des règles programmées ; lorsqu’un modèle "
                 "d’IA a rédigé ou traduit un texte, le texte l’indique. Personne n’a vérifié chaque page. Les "
                 "documents originaux font foi."),
        "more": "L’IA dans ce projet",
        "short": "Produit avec l’aide d’une IA ; non vérifié par une personne",
    },
    "nl": {
        "heading": "Informatie over AI.",
        "rules": ("Deze pagina is automatisch gemaakt door software die met hulp van AI is geschreven "
                  f"({SOFTWARE}). Geen enkel AI-model heeft de tekst geschreven: ze wordt met geprogrammeerde regels "
                  "uit de notulen gehaald. Niemand heeft ze gecontroleerd en ze kan fouten bevatten. De originele "
                  "documenten zijn leidend."),
        "extraction": ("Deze weergave van de notulen is automatisch gemaakt door software die met hulp van AI is "
                       f"geschreven ({SOFTWARE}). Geen AI-model heeft de tekst herschreven: het zijn de eigen woorden "
                       "van het gemeentebestuur, uit de pdf gehaald; pagina’s die met OCR zijn gelezen zijn "
                       "gemarkeerd en kunnen verkeerd gelezen zijn. Niemand heeft ze gecontroleerd. De originele pdf "
                       "is leidend."),
        "summary": ("Deze samenvatting is geschreven door een AI-model ({model}) op basis van de tekst van de notulen, "
                    "met software die zelf met hulp van AI is geschreven. Niemand heeft ze gecontroleerd. Ze kan "
                    "fouten, weglatingen of verzonnen details bevatten; vertrouw er niet op voor beslissingen. De "
                    "notulen en de originele pdf zijn leidend."),
        "translation": ("Deze tekst is vertaald door een AI-model ({model}) uit het Franse origineel. Geen "
                        "moedertaalspreker heeft ze nagelezen. Ze kan fouten bevatten of een nuance veranderen. De "
                        "Franse tekst is leidend."),
        "summary_translation": ("Dit is een AI-vertaling ({model}) van een Franse samenvatting die zelf door een "
                                "AI-model is geschreven. Niemand heeft een van beide gecontroleerd. De Franse notulen "
                                "en de originele pdf zijn leidend."),
        "site": ("Deze website en de software erachter zijn met hulp van AI geschreven "
                 f"({SOFTWARE}). De meeste pagina’s worden met geprogrammeerde regels gemaakt; waar een AI-model een "
                 "tekst heeft geschreven of vertaald, staat dat bij de tekst. Niemand heeft elke pagina "
                 "gecontroleerd. De originele documenten zijn leidend."),
        "more": "AI in dit project",
        "short": "Met hulp van AI gemaakt; niet door een persoon gecontroleerd",
    },
}
KINDS = ("rules", "extraction", "site", "summary", "translation", "summary_translation")


def text(kind, lang="en", model=None):
    """The disclosure sentence(s) for `kind` in `lang`; `model` names the AI model when one wrote the text."""
    if kind not in KINDS:
        raise ValueError(f"unknown disclosure kind {kind!r}")
    body = _TEXT[lang][kind]
    if "{model}" in body:
        if not model:
            raise ValueError(f"disclosure kind {kind!r} needs the model name")
        body = body.replace("{model}", model)
    return body


def markdown(kind, lang="en", model=None):
    """A one-paragraph Markdown blockquote with the disclosure and a link to AI.md."""
    t = _TEXT[lang]
    return f"> **{t['heading']}** {text(kind, lang, model)} [{t['more']}]({AI_PAGE_URL})"


def html(kind, lang="en", model=None):
    """The same notice as an HTML paragraph (already escaped)."""
    import html as _html
    t = _TEXT[lang]
    return (f'<p class="ai"><strong>{_html.escape(t["heading"])}</strong> {_html.escape(text(kind, lang, model))} '
            f'<a href="{AI_PAGE_URL}">{_html.escape(t["more"])}</a></p>')


def produced_by(kind, model=None):
    return {"rules": "software (programmed rules) written with AI assistance",
            "site": "software and documents written with AI assistance",
            "extraction": "software (extraction and OCR) written with AI assistance",
            "summary": f"AI model ({model})", "translation": f"AI model ({model})",
            "summary_translation": f"AI model ({model})"}[kind]


def front_matter(kind, model=None):
    """Machine-readable fields for a Markdown file's front matter."""
    return {"produced_by": f'"{produced_by(kind, model)}"', "human_reviewed": "false", "ai_disclosure": AI_PAGE_URL}


def labels(kind, model=None):
    """The same, for a JSON file's `labels` object."""
    return {"produced_by": produced_by(kind, model), "human_reviewed": False, "ai_disclosure": AI_PAGE_URL,
            "disclaimer": text(kind, "en", model)}


def with_front_matter(body, title, kind="rules", model=None):
    """Prefix a generated Markdown page with machine-readable front matter (the visible notice is in `body`)."""
    lines = ["---", f'title: "{title}"', "machine_generated: true"]
    lines += [f"{k}: {v}" for k, v in front_matter(kind, model).items()]
    return "\n".join(lines + ["---", ""]) + body

